#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Update default config files
cp -ru /defaults/nginx/ /config/

# precreate log files
for file in /config/log/nginx/access.log /config/log/nginx/error.log; do
    if [[ ! -f "${file}" ]]; then
        touch "${file}"
    fi
done
