#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# remove old samples
find /config/nginx/ \
    -name "*.conf.sample" \
    -type f \
    -delete

# copy new samples
find /defaults/nginx/ \
    -maxdepth 1 \
    -name "*.conf.sample" \
    -type f \
    -exec cp "{}" /config/nginx/ \;
