#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/{keys,www} \
    /config/log/nginx \
    /config/nginx/site-confs \
    /run \
    /var/lib/nginx/tmp/client_body \
    /var/tmp/nginx
